repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "23.10.1"
    hooks:
      - id: black-jupyter